$foreground = rgb(d8d5cb)
$color0 = rgb(111312)
$color1 = rgb(906A33)
$color2 = rgb(9A744B)
$color3 = rgb(C37A43)
$color4 = rgb(AF8D5A)
$color5 = rgb(C5A657)
$color6 = rgb(65858A)
$color7 = rgb(d8d5cb)
$color8 = rgb(97958e)
$color9 = rgb(906A33)
$color10 = rgb(9A744B)
$color11 = rgb(C37A43)
$color12 = rgb(AF8D5A)
$color13 = rgb(C5A657)
$color14 = rgb(65858A)
$color15 = rgb(d8d5cb)
