$foreground = rgb(a6bbd4)
$color0 = rgb(0a1013)
$color1 = rgb(375E72)
$color2 = rgb(485C74)
$color3 = rgb(3A608A)
$color4 = rgb(4D6C92)
$color5 = rgb(5377A6)
$color6 = rgb(5673CF)
$color7 = rgb(a6bbd4)
$color8 = rgb(748294)
$color9 = rgb(375E72)
$color10 = rgb(485C74)
$color11 = rgb(3A608A)
$color12 = rgb(4D6C92)
$color13 = rgb(5377A6)
$color14 = rgb(5673CF)
$color15 = rgb(a6bbd4)
