
source = $HOME/.cache/wal/colors-hyprland.conf

general {
    hide_cursor = true
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =

    path = $HOME/.cache/wal/current-wallpaper
    color = $background


    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

label {
    monitor =
    text = $TIME
    color = $foreground
    font_size = 90
    font_family = GeistMono Nerd Font ExtraBold
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +'%A, %d %B')</span>"
    color = $color7
    font_size = 20
    font_family = GeistMono Nerd Font
    position = 0, 70
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true

    outer_color = $color4
    inner_color = alpha($background, 0.5)
    font_color = $foreground

    fade_on_empty = true
    rounding = -1
    hide_input = false

    check_color = $color2
    fail_color = $color1
    fail_text = <i>Wrong Password (<b>$ATTEMPTS</b>)</i>

    position = 0, -40
    halign = center
    valign = center
}
