[theme.templates.user.terminal-sequences]
input_path = '~/.config/noctalia/templates/terminal-sequences'
output_path = '~/.cache/terminal-sequences'
post_hook = 'tee /dev/pts/[0-9]* < ~/.cache/terminal-sequences'
